import type {
  FloatingTokenLayout,
  FloatingTokensState,
} from "./types";

const HIDDEN_LAYOUT: FloatingTokenLayout[] = [
  {
    id: 1,
    imageIndex: 0,
    x: 8,
    y: -15,
    width: 10,
    rotation: -20,
    opacity: 0,
    scale: 0.7,
    floatDelay: 0,
  },
  {
    id: 2,
    imageIndex: 1,
    x: 62,
    y: -15,
    width: 10,
    rotation: 18,
    opacity: 0,
    scale: 0.7,
    floatDelay: 120,
  },
  {
    id: 3,
    imageIndex: 2,
    x: 28,
    y: -15,
    width: 10,
    rotation: -10,
    opacity: 0,
    scale: 0.7,
    floatDelay: 240,
  },
  {
    id: 4,
    imageIndex: 3,
    x: 77,
    y: -15,
    width: 10,
    rotation: 25,
    opacity: 0,
    scale: 0.7,
    floatDelay: 360,
  },
  {
    id: 5,
    imageIndex: 4,
    x: 4,
    y: -15,
    width: 10,
    rotation: -25,
    opacity: 0,
    scale: 0.7,
    floatDelay: 480,
  },
  {
    id: 6,
    imageIndex: 5,
    x: 78,
    y: -15,
    width: 10,
    rotation: 14,
    opacity: 0,
    scale: 0.7,
    floatDelay: 600,
  },
];

const HOME_LAYOUT: FloatingTokenLayout[] = [
  {
    id: 1,
    imageIndex: 0,
    x: 10,
    y: 3.5,
    width: 11,
    rotation: -18,
    opacity: 1,
    scale: 1,
    floatDelay: 0,
  },
  {
    id: 2,
    imageIndex: 1,
    x: 62,
    y: 3.5,
    width: 11,
    rotation: 17,
    opacity: 1,
    scale: 1,
    floatDelay: 120,
  },
  {
    id: 3,
    imageIndex: 2,
    x: 28,
    y: 11.5,
    width: 10,
    rotation: -12,
    opacity: 1,
    scale: 1,
    floatDelay: 240,
  },
  {
    id: 4,
    imageIndex: 3,
    x: 76,
    y: 14,
    width: 14,
    rotation: 24,
    opacity: 1,
    scale: 1,
    floatDelay: 360,
  },
  {
    id: 5,
    imageIndex: 4,
    x: 7,
    y: 27,
    width: 10,
    rotation: -24,
    opacity: 1,
    scale: 1,
    floatDelay: 480,
  },
  {
    id: 6,
    imageIndex: 5,
    x: 78,
    y: 33,
    width: 10,
    rotation: 16,
    opacity: 1,
    scale: 1,
    floatDelay: 600,
  },
];

const INSTRUCTIONS_LAYOUT: FloatingTokenLayout[] = [
  {
    id: 1,
    imageIndex: 0,
    x: 73,
    y: 49,
    width: 14,
    rotation: 18,
    opacity: 1,
    scale: 1,
    floatDelay: 0,
  },
  {
    id: 2,
    imageIndex: 1,
    x: 10,
    y: 76,
    width: 17,
    rotation: -28,
    opacity: 1,
    scale: 1,
    floatDelay: 120,
  },
  {
    id: 3,
    imageIndex: 2,
    x: 30,
    y: 86,
    width: 10,
    rotation: -10,
    opacity: 0,
    scale: 0.8,
    floatDelay: 240,
  },
  {
    id: 4,
    imageIndex: 3,
    x: 60,
    y: 86,
    width: 10,
    rotation: 20,
    opacity: 0,
    scale: 0.8,
    floatDelay: 360,
  },
  {
    id: 5,
    imageIndex: 4,
    x: 5,
    y: 86,
    width: 10,
    rotation: -20,
    opacity: 0,
    scale: 0.8,
    floatDelay: 480,
  },
  {
    id: 6,
    imageIndex: 5,
    x: 80,
    y: 86,
    width: 10,
    rotation: 15,
    opacity: 0,
    scale: 0.8,
    floatDelay: 600,
  },
];

const GAME_LAYOUT: FloatingTokenLayout[] = HIDDEN_LAYOUT;

const SCORE_LAYOUT: FloatingTokenLayout[] = HOME_LAYOUT;

const PRIZE_LAYOUT: FloatingTokenLayout[] = [
  {
    id: 1,
    imageIndex: 0,
    x: 10,
    y: 4,
    width: 11,
    rotation: -18,
    opacity: 1,
    scale: 1,
    floatDelay: 0,
  },
  {
    id: 2,
    imageIndex: 1,
    x: 63,
    y: 3,
    width: 11,
    rotation: 17,
    opacity: 1,
    scale: 1,
    floatDelay: 120,
  },
  {
    id: 3,
    imageIndex: 2,
    x: 28,
    y: 12,
    width: 10,
    rotation: -12,
    opacity: 1,
    scale: 1,
    floatDelay: 240,
  },
  {
    id: 4,
    imageIndex: 3,
    x: 78,
    y: 15,
    width: 14,
    rotation: 24,
    opacity: 1,
    scale: 1,
    floatDelay: 360,
  },
  {
    id: 5,
    imageIndex: 4,
    x: 7,
    y: 29,
    width: 10,
    rotation: -24,
    opacity: 1,
    scale: 1,
    floatDelay: 480,
  },
  {
    id: 6,
    imageIndex: 5,
    x: 78,
    y: 31,
    width: 10,
    rotation: 16,
    opacity: 1,
    scale: 1,
    floatDelay: 600,
  },
];

export const FLOATING_TOKEN_LAYOUTS: Record<
  FloatingTokensState,
  FloatingTokenLayout[]
> = {
  hidden: HIDDEN_LAYOUT,
  home: HOME_LAYOUT,
  instructions: INSTRUCTIONS_LAYOUT,
  game: GAME_LAYOUT,
  score: SCORE_LAYOUT,
  prize: PRIZE_LAYOUT,
};